from __future__ import annotations


EIP1559_TRANSACTION_TYPE = 0x02
ZK_TRANSACTION_TYPE = 0x7E
LEGACY_V_OFFSET = 27
EIP155_CHAIN_ID_OFFSET = 35

INTRINSIC_GAS_BASE = 21_000
INTRINSIC_GAS_CONTRACT_CREATION = 32_000
INTRINSIC_GAS_ZERO_DATA_BYTE = 4
INTRINSIC_GAS_NON_ZERO_DATA_BYTE = 16
INTRINSIC_GAS_ACCESS_LIST_ADDRESS = 2_400
INTRINSIC_GAS_ACCESS_LIST_STORAGE_KEY = 1_900
